Fix h5py issues, hydra compatibility, YAML config, and support for DataFrames/CSV files
lappalainenj/datamate pull request #1
Opened 2024-04-07 13:26 UTC by felixp8

* Remove related packages from README
* Introduce `H5Reader` object to avoid persistent read file handles at the mercy of the garbage collector that may interfere with subsequent writes/extends.
* Switch from saving `_meta.yaml` as JSON to using YAML, while still supporting legacy JSON reading
* Avoid treating dunder attributes (with format `__*__`, e.g., `__file__`) as normal keys for attribute access, for compatibility with hydra instantiation
* Save/read `pd.DataFrame` objects as CSV instead of arrays
* Introduce single-threaded SWMR test that reproduces past h5py file lock issue but is fixed with `H5Reader` changes

2024-04-10 16:48 UTC, lappalainenj reviewed
I really like the changes and enhancements! Minor comments below

2024-04-10 16:48 UTC, lappalainenj commented on datamate/directory.py
> +                from importlib import import_module
Please import at the beginning of the file

2024-04-10 16:48 UTC, lappalainenj commented on datamate/directory.py
> +    """Wrapper around h5 read operations to prevent persistent file handles"""
Please add a comment that explains how it does so

2024-04-10 16:48 UTC, lappalainenj commented on datamate/directory.py
> +        except:  # for backwards compatibility
This will run the except code on any error. Please make sure that it does so only on the error that indicates that yaml was expected but json was found

2024-04-10 19:46 UTC, felixp8 commented on datamate/directory.py
> +        except:  # for backwards compatibility
good catch, actually ruamel.yaml can load json without error. I still want to catch this so now I'm reading with json and then trying yaml if that fails

2024-04-10 20:40 UTC, lappalainenj commented on datamate/directory.py
> +        except:  # for backwards compatibility
works, thanks!

2024-04-11 07:45 UTC, lappalainenj requested changes

2024-04-11 07:45 UTC, lappalainenj commented on tests/test_swmr.py
>      assert_directory_equals(
Could you make this test succeed?

2024-04-11 09:12 UTC, felixp8 commented on tests/test_swmr.py
>      assert_directory_equals(
if by "succeed" you mean "not exist" then yes :P

2024-04-16 08:21 UTC, merged